//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller2
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.factura_detalle = new HashSet<factura_detalle>();
        }
    
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public int id_marca { get; set; }
        public int stock { get; set; }
        public Nullable<double> precio { get; set; }
        public string descripcion { get; set; }
        public int id_categoria { get; set; }
        public string estado_producto { get; set; }
        public Nullable<int> codigo_producto { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_detalle> factura_detalle { get; set; }
        public virtual marca marca { get; set; }
    }
}
